services:
  - type: web
    name: machinelearning-entregable-2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-dashboard.txt
    startCommand: gunicorn dashboard:server --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
